
title = "blog"
explain = "code.sun个人blog"
mode = "dev"
addr = ":9088"
srv = "https://blog.feibooks.com"

jwtkey = "FeM6QdeeQafduucc"
jwtexp = 12

[author]
name = "code.sun"
website = "https://github.com/kms9"

[wechat]
appid = "appid"
secret = "secret"

[database]
host = "127.0.0.1"
port = 3306
user = "root"
passwd = "mysql123456"
dbname = "goblog"
params = "charset=utf8&parseTime=true"

[xorm]
idle = 4
open = 8
show = true
sync = false
cache_enable = false
cache_count = 1000

